// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFykvYaWkSmE13hhPRGJkWEBDTiXP6t6Q',
    appId: '1:190730477461:web:61b5ed41aabfae3630e09c',
    messagingSenderId: '190730477461',
    projectId: 'hogwarts-59cae',
    authDomain: 'hogwarts-59cae.firebaseapp.com',
    databaseURL: 'https://hogwarts-59cae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hogwarts-59cae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjIlMTCPp1kVhSWKrf-V0kSism3Qe4wR0',
    appId: '1:190730477461:android:911193300f0d353b30e09c',
    messagingSenderId: '190730477461',
    projectId: 'hogwarts-59cae',
    databaseURL: 'https://hogwarts-59cae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hogwarts-59cae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAghukSg9nD4FNIMwVVGgckCnHuE-9AwK0',
    appId: '1:190730477461:ios:2902c972a56e887230e09c',
    messagingSenderId: '190730477461',
    projectId: 'hogwarts-59cae',
    databaseURL: 'https://hogwarts-59cae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hogwarts-59cae.firebasestorage.app',
    iosBundleId: 'com.example.harryPotter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAghukSg9nD4FNIMwVVGgckCnHuE-9AwK0',
    appId: '1:190730477461:ios:2902c972a56e887230e09c',
    messagingSenderId: '190730477461',
    projectId: 'hogwarts-59cae',
    databaseURL: 'https://hogwarts-59cae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hogwarts-59cae.firebasestorage.app',
    iosBundleId: 'com.example.harryPotter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFykvYaWkSmE13hhPRGJkWEBDTiXP6t6Q',
    appId: '1:190730477461:web:7a361a1544a4ce1330e09c',
    messagingSenderId: '190730477461',
    projectId: 'hogwarts-59cae',
    authDomain: 'hogwarts-59cae.firebaseapp.com',
    databaseURL: 'https://hogwarts-59cae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hogwarts-59cae.firebasestorage.app',
  );

}