# Generated by Django 5.1.7 on 2025-04-01 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresonerPolicia',
            fields=[
                ('idPresonerPolicia', models.AutoField(primary_key=True, serialize=False)),
                ('policia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Presoners',
            fields=[
                ('idPresoner', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=1750, verbose_name='nom')),
                ('edat', models.IntegerField(verbose_name='edat')),
                ('motiuDetencio', models.CharField(max_length=1750, verbose_name='motiuDetencio')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('policia', models.ManyToManyField(through='examen.PresonerPolicia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='presonerpolicia',
            name='presoners',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.presoners'),
        ),
    ]
