baseURL = 'https://marcs.damvib.cat/'
languageCode = 'cat-es'
title = 'Pàgina web'
theme = 'docsy'

[module]
  proxy = "direct"
  # uncomment line below for temporary local development of module
  # replacements = "github.com/google/docsy -> ../../docsy"
  [module.hugoVersion]
    extended = true
    min = "0.73.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/FortAwesome/Font-Awesome"
    disable = false
  [[module.imports]]
    path = "github.com/twbs/bootstrap"
    disable = false
