DROP DATABASE ActivitatsExtraescolars;

CREATE DATABASE ActivitatsExtraescolars;

USE ActivitatsExtraescolars;

CREATE TABLE Towns (
	TownId		INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	Name		VARCHAR(30) NOT NULL UNIQUE,
	Population	INT UNSIGNED NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

CREATE TABLE Schools (
	SchoolCode	CHAR(6) NOT NULL PRIMARY KEY,
	Name		VARCHAR(30) NOT NULL,
	TownId		INT UNSIGNED NOT NULL,
	CONSTRAINT FOREIGN KEY (TownId) REFERENCES Towns(TownId)
		ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

CREATE TABLE Children (
	Code		CHAR(9) NOT NULL PRIMARY KEY,
	FirstName	VARCHAR(40) NOT NULL,
	LastName	VARCHAR(60) NOT NULL,
	Phone		INT,
	TownId		INT UNSIGNED NOT NULL,
	SchoolCode	CHAR(6) NOT NULL,
	CONSTRAINT FOREIGN KEY (TownId) REFERENCES Towns(TownId)
		ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT FOREIGN KEY (SchoolCode) REFERENCES Schools(SchoolCode)
		ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

CREATE TABLE Activities (
	ActivityId	INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	Name		VARCHAR(50) NOT NULL UNIQUE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

CREATE TABLE ActivityOffers (
	SchoolCode	CHAR(6) NOT NULL,
	ActivityId	INT UNSIGNED NOT NULL,
	Score		INT NOT NULL,
	Capacity	INT NOT NULL,
	CONSTRAINT PRIMARY KEY (SchoolCode, ActivityId),
	CONSTRAINT FOREIGN KEY (SchoolCode) REFERENCES Schools(SchoolCode)
		ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT FOREIGN KEY (ActivityId) REFERENCES Activities(ActivityId)
		ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

