# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.hostname = "segonparcial"
  config.vm.define "segonparcial"
  config.vm.network "private_network", ip: "192.168.56.67", netmask: "255.255.248.0"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.cpus = 1
  end
end