# Generated by Django 5.1.7 on 2025-03-25 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumne',
            fields=[
                ('idAlumnes', models.AutoField(primary_key=True, serialize=False)),
                ('nomComplet', models.CharField(max_length=255, verbose_name='nomComplet')),
                ('questionari', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Questionari',
            fields=[
                ('idQuestionaris', models.AutoField(primary_key=True, serialize=False)),
                ('idEmpresa', models.IntegerField(verbose_name='idEmpresa')),
                ('descripcio', models.CharField(max_length=255, verbose_name='descripcio')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunte',
            fields=[
                ('idPreguntes', models.AutoField(primary_key=True, serialize=False)),
                ('descripcio', models.CharField(max_length=255, verbose_name='descripcio')),
                ('questionari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enquestes.questionari')),
            ],
        ),
        migrations.CreateModel(
            name='Resposte',
            fields=[
                ('idRespostes', models.AutoField(primary_key=True, serialize=False)),
                ('valoracio', models.IntegerField()),
                ('tancar', models.BooleanField(default=False)),
                ('idAlumne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enquestes.alumne')),
                ('idPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enquestes.pregunte')),
                ('idProfessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='alumne',
            name='preguntes',
            field=models.ManyToManyField(through='Enquestes.Resposte', to='Enquestes.pregunte'),
        ),
        migrations.AddField(
            model_name='alumne',
            name='professors',
            field=models.ManyToManyField(through='Enquestes.Resposte', to=settings.AUTH_USER_MODEL),
        ),
    ]
