# Generated by Django 5.1.7 on 2025-03-28 15:28
from django.contrib.auth.models import User, Group
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enquestes', '0001_initial'),
    ]

    def create_questionari(apps, schema_editor):
        Questionari = apps.get_model('Enquestes', 'Questionari')
        Questionari.objects.create(idEmpresa=1, descripcio='Qüestionari de prova')

    def create_alumne(apps, schema_editor):
        Alumne = apps.get_model('Enquestes', 'Alumne')
        Alumne.objects.create(nomComplet='Eloi', questionari=False)

    def create_pregunta(apps, schema_editor):
        Pregunta = apps.get_model('Enquestes', 'Pregunte')
        Pregunta.objects.create(descripcio='Pregunta de prova', questionari_id=1)

    def create_user(apps, schema_editor):
        # python manage.py makemigrations --empty Enquestes
        User.objects.create_user(username='eloi', password='super3', email='eloi@correu.cat')
        User.objects.create_user(username='hector', password='super3', email='hector@correu.cat')
        Group.objects.get_or_create(name='Professor')
        Group.objects.get_or_create(name='Coordinador')
        my_group = Group.objects.get(name='Professor')
        my_group.user_set.add(1)
        my_group = Group.objects.get(name='Coordinador')
        my_group.user_set.add(2)

    operations = [
        migrations.RunPython(create_questionari),
        migrations.RunPython(create_alumne),
        migrations.RunPython(create_pregunta),
        migrations.RunPython(create_user)
    ]
